### ISSUE TITLE
What do you mean by Volatile and Non Volatile data?

### ISSUE THREAD

**Issue by Sheraff** [shawnrice/alfred-documentation#2]
I'm wondering what should be considered as volatile and what shouldn't.
- I'm guessing anything that is actually included in the workflow doesn't fit in these because it's in the workflow folder.
- Anything that is essential for the workflow to run properly, but is downloaded afterwards is Non Volatile?
- User preferences / user data? Seems to me that you never really want to get rid of these but they don't prevent the workflow from working.
- Databases? Any knowledge that isn't meant as a cache could be considered Non Volatile?
- Images? Like thumbnails. They aren't vital at all, can be redownloaded often, but don't have to. Is this volatile or non volatile?
- Cached pages / cached results? I'm assuming this is Volatile.

The page could use more explanation I guess :-)

https://github.com/shawnrice/alfred-documentation/wiki/Best-Practices-for-Workflows

**Comment by shawnrice** [comment]
It does need clarification (feel free to clarify it).

So: volatile is cache, and non-volatile is data. Generally, I think that you shouldn't bundler data in your workflow because, if you separate it, then you don't have to update the workflow when updating the data. The workflow is code, and the data is, well, data.

Say you download an image, a movie poster or something. Will it be a canonical representation of some data? If so, it's data. Will it be something that might change (often enough)? If yes, it is cache. 

If you're working to speed up the results of a search by caching them, then, obviously, they're cache. Do you have an image that represents the front-page of a URL that you want to keep? Yes, but, we might imagine that the image that represents the front-page might change out often enough (weekly? monthly?), then it's cache.

If the downloaded data might mis-represent later search results (or any query) because the remote data might change, then it's cache. If the data won't change, then it's data.

You can cache a Wikipedia page, but, since those can change (and do often enough), then they're cache rather than data.

You can wipe the cache without significantly damaging the workflow, but wiping the data might. Say that you're building a workflow that is supposed to view weather data but also keep a record of it. Then, the latest search (within "x" time) is cache, but it's also saved as data because the query is not available later.

If you have a mechanism to clear the downloaded or generated content, then it's cache. (This doesn't count a radical reboot mechanism for the workflow, basically a "clean install" or a rollback to defaults).

If you're saving a "last-run" timestamp, then that's cache. If you're saving a "first-run" file flag, then that's data.

User preferences are slightly different because you want to save the preferences. Thus, the preferences as a file, while the individual preferences might change, should stick around.

I think that the ground rule is that if you select your words carefully, then; if you want to "save" something, it's data. If you want to "cache" something, then it's volatile.

But, yes, this should be better clarified on the page.

**Comment by Sheraff** [comment]
Thanks :) That does make it very clear. The terms volatile and non volatile are pretty explicit by themselves but your series of examples and the simplification with data / cache make it limpid. I think this is the sort of thing that should be on the doc page.

**Comment by deanishe** [comment]
Hmm. I thought the description was clear enough (though, I suppose I would, as I wrote that part of it).

I'll add a couple of examples to the wiki page.

**Comment by deanishe** [comment]
I've tried to clarify the page. Would you have a look @Sheraff and see if it's any clearer?

IMO, using the terms "volatile" and "non-volatile" is bad. I know they're technically the correct terms, but I think they're confusing to non-coders.

**Comment by Sheraff** [comment]
Sounds good now. Very understandable.
