### ISSUE TITLE
Combine pages "Libraries" and "Workflow Libraries and Helpers"?

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-documentation#4]
They seem to serve essentially the same purpose.

Shouldn't the content of "[Libraries](https://github.com/shawnrice/alfred-documentation/wiki/Libraries)" be moved to "[Workflow Libraries and Helpers](https://github.com/shawnrice/alfred-documentation/wiki/Workflow-Libraries-and-Helpers)" and the former page deleted?

**Comment by shawnrice** [comment]
Yes.

I'm assuming one was an earlier page.

**Comment by shawnrice** [comment]
Done.

**Comment by deanishe** [comment]
:+1: I've changed the Home page to match. I can't (or don't know how to) change the **Pages** list in the right-hand sidebar. Could you remove the **Libraries** link from there?

**Comment by shawnrice** [comment]
That's automatically generated from the pages that exist (I haven't figured
out how to customize it either, but I haven't looked that hard).

So, I think we'd have to delete the page, which is possible. I opted to
leave a link to the new one rather than delete it, but if you'd like, then
just delete the page.

**Comment by deanishe** [comment]
Deleted.
